ARG PHP_VERSION=8.1
FROM php:${PHP_VERSION}-cli

# Install dependencies
RUN apt-get update && apt-get install -y \
    subversion \
    git \
    unzip \
    libzip-dev \
    default-mysql-client \
    && docker-php-ext-install mysqli zip

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Install WP-CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

WORKDIR /app
